### ISSUE TITLE
Loading model shows a name that is not defined: CLIP_SIMCLR_VITB16

### ISSUE THREAD

**Issue by TonyLianLong** [facebookresearch/SLIP#3]
I'm trying to load a model and it shows the model name above. The name doesn't exist in models.py, and I believe it should be SLIP_VITB16.

**Comment by fly-dragon211** [comment]
I have the same error.
```
    model = getattr(models, old_args.model)(rand_embed=False,
AttributeError: module 'models' has no attribute 'CLIP_SIMCLR_VITB16'
```

**Comment by thepowerfuldeez** [comment]
Hello! Try SLIP_VITB16, you can check in the code: https://github.com/facebookresearch/SLIP/blob/d22cce85ecb11764658b6679212b4306262bccf2/models.py#L303

**Comment by normster** [comment]
Thanks for pointing this out everyone! The checkpoints will be fixed and re-uploaded this week but in the meantime you can replace  `old_args.model` with the correct model string, i.e. `SLIP_VITB16` in this case.
