### ISSUE TITLE
How use SLIP to do text-to-image retrieval?

### ISSUE THREAD

**Issue by fly-dragon211** [facebookresearch/SLIP#5]
Could we use the feature that produced by model.encode_text and model.encode_image function, just as CLIP.

**Comment by fly-dragon211** [comment]
I use the feature that produced by model.encode_text and model.encode_image function. While the performance is lower than CLIP.

**Comment by normster** [comment]
Hi @fly-dragon211, you should be able to use the `encode_text` and `encode_image` methods to compute text/image features for retrieval. As you mentioned, performance is lower than CLIP because we our models are trained on a smaller dataset.
