### ISSUE TITLE
Number of text transformer layers

### ISSUE THREAD

**Issue by LiJunnan1992** [facebookresearch/SLIP#6]
Hi, thanks for the amazing code!

I have one question about the number of text transformer layers. In the paper it says that the text transformer contains 38M parameters. However, your code seems to use the 12-layer 512-wide model with 8 attention heads, which contains 63M parameter according to the CLIP paper. May I know which one is used?

Thanks a lot!

Best,
Junnan

**Comment by normster** [comment]
Hi Junnan, thanks for pointing this out! That is the correct text model. I forgot to include the 25M embedding parameters when counting the parameters, and our model should be described as 68M parameters. Sorry for the confusion!
